// SPDX-License-Identifier: Apache-2.0

// Package timeline generates human-readable incident reports from agent
// execution, migration, and replay events. This is the product output
// for the reconciliation demo — an incident report that answers
// "what happened?" immediately.
package timeline

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// EventKind categorizes timeline entries.
type EventKind int

const (
	KindStateChange   EventKind = iota // Agent state machine transition
	KindCheckpoint                     // Checkpoint saved
	KindCrash                          // Host node failure
	KindMigration                      // Agent migrated to new node
	KindReplay                         // Replay verification result
	KindSideEffect                     // External side effect executed
	KindSkippedAction                  // Action skipped (idempotency)
	KindCompletion                     // Case completed
	KindInfo                           // Informational event
)

// Event represents a single timeline entry.
type Event struct {
	Timestamp  time.Time
	Node       string // "node-a" or "node-b"
	TickNumber uint64
	Kind       EventKind
	Summary    string
	Details    []string // indented sub-lines
}

// SafetyCheck holds the result of a safety verification.
type SafetyCheck struct {
	Label  string
	Passed bool
}

// Timeline collects events and renders them as an incident report.
type Timeline struct {
	CaseID  string
	AgentID string
	Events  []Event
}

// New creates a new timeline.
func New(caseID, agentID string) *Timeline {
	return &Timeline{
		CaseID:  caseID,
		AgentID: agentID,
	}
}

// Add appends an event to the timeline.
func (t *Timeline) Add(ev Event) {
	t.Events = append(t.Events, ev)
}

// separator is the width of the report border.
const separator = "==============================================================="

// Render writes the formatted incident timeline to w.
func (t *Timeline) Render(w io.Writer) {
	fmt.Fprintln(w)
	fmt.Fprintln(w, separator)
	fmt.Fprintf(w, " INCIDENT TIMELINE — Case %s\n", t.CaseID)
	fmt.Fprintf(w, " Agent: %s\n", t.AgentID)
	fmt.Fprintln(w, " Generated by Igor replay engine")
	fmt.Fprintln(w, separator)
	fmt.Fprintln(w)

	for _, ev := range t.Events {
		ts := ev.Timestamp.Format("15:04:05")
		prefix := " "

		// Crash events get a special marker.
		if ev.Kind == KindCrash {
			prefix = " \u2717"
		}

		fmt.Fprintf(w, "%s %s  %s\n", prefix, ts, ev.Summary)

		for _, detail := range ev.Details {
			fmt.Fprintf(w, "            %s\n", detail)
		}

		fmt.Fprintln(w)
	}
}

// RenderSafetySummary writes the safety verification block.
func (t *Timeline) RenderSafetySummary(w io.Writer, checks []SafetyCheck) {
	fmt.Fprintln(w, separator)
	fmt.Fprintln(w, " SAFETY SUMMARY")

	for _, check := range checks {
		mark := "\u2713" // checkmark
		if !check.Passed {
			mark = "\u2717" // cross
		}
		fmt.Fprintf(w, " %s %s\n", mark, check.Label)
	}

	fmt.Fprintln(w, separator)
	fmt.Fprintln(w)
}

// RenderComparison writes the side-by-side naive vs Igor comparison.
func (t *Timeline) RenderComparison(w io.Writer) {
	fmt.Fprintln(w)
	fmt.Fprintln(w, strings.Repeat("—", 63))
	fmt.Fprintln(w, " COMPARISON: Naive Worker vs Igor")
	fmt.Fprintln(w, strings.Repeat("—", 63))
	fmt.Fprintln(w)
	fmt.Fprintln(w, " Naive Worker (typical automation):")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "   Finalize called")
	fmt.Fprintln(w, "   Process crashed")
	fmt.Fprintln(w, "   Process restarted")
	fmt.Fprintln(w, "   State unclear — did finalize go through?")
	fmt.Fprintln(w, "   Options:")
	fmt.Fprintln(w, "     a) Retry finalize  -> risk: double execution")
	fmt.Fprintln(w, "     b) Skip finalize   -> risk: stuck transaction")
	fmt.Fprintln(w, "     c) Wake up human   -> cost: hours of investigation")
	fmt.Fprintln(w)
	fmt.Fprintln(w, " Igor Worker:")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "   Finalize intent recorded with idempotency key")
	fmt.Fprintln(w, "   Node failed")
	fmt.Fprintln(w, "   Agent migrated, resumed from checkpoint")
	fmt.Fprintln(w, "   Replay verified — intent already committed, skip duplicate")
	fmt.Fprintln(w, "   Ack received, case completed")
	fmt.Fprintln(w, "   Timeline generated — full incident proof")
	fmt.Fprintln(w)
	fmt.Fprintln(w, strings.Repeat("—", 63))
	fmt.Fprintln(w)
}
